---
- hosts: webservers
  become: True
  gather_facts: True
  tasks:
    - name: Install packages
      yum:
        name: "{{ item }}"
        state: "present"
      when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7")
      loop:
        - httpd
        - git
        - wget
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
