# when - condition playbook

--- # to install and start httpd and apache2
- hosts: all
  become: true 
  tasks:
    - name: install httpd
      yum: pkg=httpd state=installed
      when: ansible_distribution == "RedHat"

    - name: install apache2
      apt: pkg=apache2 state=latest
      when: ansible_distribution == "Ubuntu"

    - name: start httpd
      service: name=httpd state=started enable=true
      when: ansible_distribution == "RedHat"

    - name: start apache2
      service: name=apache2 state=started enable=true
      when: ansible_distribution == "Ubuntu"

    - name: deploy hello.html
      copy: src=/home/vagrant/hello.html dest=/var/www/html/
      when: ansible_distribution == "RedHat"

    - name: deploy hello.html
      copy: src=/home/vagrant/hello.html dest=/var/www/html/
      when: ansible_distribution == "Ubuntu"

