--- # when - condition playbook 
- name: Loop & Task Control
  hosts: webservers
  become: true
  vars:
    install_package: "ok"
    supported_os:
      - RedHat
      - Fedora
      - CentOS
    min_memory: 100
    userlist:
      - user101
      - user102
      - user103
  tasks:
    - name: Show users 
      debug:
        msg: "{{ item }}"
      with_list: "{{ userlist }}"
      
    - name: Create users 
      user:
        name: "{{ item }}"
      with_list: "{{ userlist }}"

    - name: Install Packages
      yum:
        name:
          - httpd
          - firewalld
        state: present
      when: 
        - install_package == "ok"
        - ansible_distribution in supported_os
        - min_memory is defined

    - name: Enable Service
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - httpd
        - firewalld
     
