--- 
- name: Ansible Facts
  hosts: webservers
  gather_facts: false
  tasks:
    - name: collect facts 
      setup:
    - name: Show details
      debug:
        msg: "{{ ansible_distribution }} {{ ansible_hostname }} {{ ansible_default_ipv4['address'] }}"

