---
- hosts: all
  become: true 
  gather_facts: false  
  tasks:
    - name: install httpd
      yum: pkg=httpd state=installed

    - name: start httpd
      service: name=httpd state=started

    - name: deploy hello.html
      copy: src=/home/vagrant/hello.html dest=/var/www/html/

# gather_facts: false -  It wont check or gather the remote machine information