--- 
- name: Handlers
  hosts: webservers
  become: yes
  tasks:
    - name: Install httpd and firewalld
      yum:
        name:
          - httpd
          - firewalld
        state: latest
      notify: 
        - restart httpd

    - name: Enable and Run Firewalld
      service: 
        name: firewalld
        enabled: true 
        state: started 
    - name: firewalld permit httpd service 
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes 
        
    - name: Test html page is installed
      copy:
        content: "Welcome to the example.com internet!\n"
        dest: /var/www/html/index.html
      notify: 
        - restart httpd

  handlers:
    - name: restart httpd
      service: 
        name: httpd
        enabled: true
        state: restarted

- name: Test internet web server 
  hosts: localhost
  become: no
  tasks:
    - name: connect to internet webserver
      uri:
        url: http://becode.org
        status_code: 200
     
