---
- name: managing the file permissions using ansible
  hosts: server1
  become: yes
  become_user: root
  tasks:
    - name: Create a new file with permissions
      file:
        name: "{{ item.location }}"
        state: touch
        mode: "{{ item.mode }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
      register: task1
      with_items:
        - { location: "/tmp/file1.txt", mode: "566", owner: root, group: root }
        - { location: "/tmp/file2.txt", mode: "766", owner: root, group: root }
    - name: Printing the result of task1
      debug:
        msg: "{{ task1 }}"
