# With in the loop :
#  with_items

--- 
- name: Loop & Task Control
  hosts: webservers
  become: true
  vars:
    userlist:
      - user101
      - user102
      - user103
  tasks:
    - name: Show users 
      debug:
        msg: "{{ item }}"
      with_list: "{{ userlist }}"
      
    - name: Create users 
      user:
        name: "{{ item }}"
      with_list: "{{ userlist }}"

    - name: Install Packages
      yum:
        name:
          - httpd
          - firewalld
        state: present
    - name: Enable Service
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - httpd
        - firewalld
     

# ---------------------------------------------

---
- name: Create multiple files
  hosts: webservers
  become: true
  tasks:
    - name: create multiple files
      file:
        name: "{{ item }}"
        state: touch
        mode: 0775
        owner: root
        group: root
      with_items:
        - test.log
        - devops.cfg
        - file1.txt
        - devdb.properties

# -----------------------------------------

---
- name: delete files
  hosts: webservers
  become: true
  tasks:
    - name: delete multiple files
      file:
        path: /home/vagrant/ {{ item }}
        state: absent
        mode: 755
        owner: root
        group: root
      with_items:
        - test.log
        - devops.cfg
        - file1.txt
        - devdb.properties

# -----------------------------------------

---
- name: Createion permissions
  hosts: webservers
  become: true
  tasks:
    - name: Create multiple files example
      file:
        path: "{{ item.location }}"
        state: touch
        mode: "{{ item.mode }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
      with_items:
        - { location: "file1.txt", mode: "566", owner: root, group: root }
        - { location: "file2.txt", mode: "766", owner: root, group: root }
