---
- name: Install httpd and firewalld
  hosts: server1
  become: yes
  become_user: root
  tasks:
    - name: yum update
      yum:
        name: "*"
        state: latest

    - name: Install httpd and firewalld
      yum:
        name:
          - httpd
          - firewalld
        state: latest

    - name: start httpd
      ansible.builtin.systemd:
        enabled: yes
        name: httpd
        state: started

    - name: start firewalld
      ansible.builtin.systemd:
        enabled: yes
        name: firewalld
        state: started
