---
- name: Create multiple files
  hosts: server1
  become: yes
  become_user: root
  vars_files:
    - user-passwd.yml
  tasks:
    - name: create files
      user:
        name: "{{ username }}"
        password: "{{ passwd | password_hash('sha256') }}"
