--- 
- name: Create users
  hosts: webservers
  become: true 
  vars_files:
    - vars2.yml
  tasks:
    - name: Show users
      debug:
        msg: "{{ users['john']['firstname'] }}"
        #msg: "{{ users.john.lastname }}"


