---
- name: Install httpd and firewalld
  hosts: server1
  become: yes
  become_user: root
  vars_files
    - vars.yml

  tasks:
    - name: yum update
      yum:
        name: "*"
        state: latest

    - name: Install {{ web_package }} & {{ firewall_package }}
      yum:
        name:
          - "{{ web_package }}"
          - "{{ firewall_package }}"
        state: latest

    - name: start {{ web_package }}
      ansible.builtin.systemd:
        enabled: yes
        name: "{{ web_package }}"
        state: started

    - name: start {{ firewall_package }}
      ansible.builtin.systemd:
        enabled: yes
        name: "{{ firewall_package }}"
        state: started
