--- # Variables
- name: Install and configure httpd
  hosts: webservers
  become: yes 
  vars:
  vars_files:
  tasks:
    - name: Include vars 
      include_vars: vars.yml

    - name: Install {{ web_package }} & {{ firewall_package }}
      yum: 
        name:
          - "{{ web_package }}"
          - "{{ firewall_package }}"
        state: latest
    - name: Enable and Start {{ web_service }}
      service:
        name: "{{ web_service }}"
        enabled: true 
        state: started
    - name: Enable and Start {{ firewall_service }}
      service:
        name: "{{ firewall_service }}" 
        enabled: true 
        state: started
    
    - name: Open {{ firewall_service }} ports 
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes 
    - name: Copy html content 
      copy: 
        content: "Welcome to our website <br>(This is deployed using Ansible)"
        dest: /var/www/html/index.html

- name: Test and Verify webservers
  hosts: localhost
  become: no 
  tasks:
    - name: Connect to the webserver
      uri: 
        url: http://server1
        status_code: 200