---
- name: Ansible vault playbook
  hosts: all
  become: true
  vars:
    pwd: poukal
  tasks:
    - name: creating user account and setting the password
      user:
        name: thierno
        password: "{{ pwd }}"
        debug:
        var: pwd

# -----------------------------------------

---
- name: Ansible vault playbook
  hosts: all
  become: true
  vars_files:
    - /home/vagrant/mypasswd.yml
  tasks:
    - name: creating user account and setting the password
      user:
        name: thierno
        password: "{{ pwd }}"
