--- 
- name: Using Secrets in Playbook
  hosts: webservers
  become: true
  vars_files:
    - user-passwd.yml
  tasks:
    - name: Create User
      user:
        name: "{{ username }}"
        password: "{{ passwd | password_hash('sha256') }}"


# ansible-vault encrypt user-passwd.yml
# ansible-playbook -i inventory --vault-id @prompt site.yml
# ssh newuser@server1
