---
- hosts: webservers
  become: yes
  tasks:
    - name: register date and check
      shell: |
        date
        ifconfig
        uptime
        hostname

      register: out

    - name: debug messages
      debug:
        var: out
